databases:
  - name: ratebeer
    databaseName: ratebeer
    user: ratebeer
    plan: free
    region: frankfurt

services:
  - type: web
    name: ratebeer
    runtime: ruby
    plan: free
    region: frankfurt
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ratebeer
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
